### ISSUE TITLE
Not being able to get a Datatable

### ISSUE THREAD

**Issue by Jacocococo** [FabianFG/JFortniteParse#5]
To start off, I want to say, that I'm not sure if this is a bug/not implemented or if I simply don't know how to do it.

I've been trying for a few days now to export the RangedWeapons datatable (for the stats of the ranged weapons in StW), but I can't figure out how to get the table as a json file.

I'm using this with Java and not Kotlin

When I try to load the file and use .toJson(), it doesn't give the stats. Then I tried different things with UExport and FObjectExport objects, and finally today with a UDataTable, but I can't figure out how to get it into the Data Table from that either.
I thought the .serialize(FAssetArchiveWriter) would do it, but that makes it into a .uexp file instead

So am I just doing something wrong, or is it not possible to get the datatables?

**Comment by FabianFG** [comment]
Yes that's actually true. It is normal that it doesn't appear in the .toJson() method of the Package class, but there should be an additional method for that UDataTable. I will add that

**Comment by FabianFG** [comment]
added these methods in 3.1.12

**Comment by Jacocococo** [comment]
After compiling the source code for v3.5.13, I noticed that the UDataTable.toJson() method had stopped working

I managed to make a fix for myself, which was by changing the method to this code

`fun toJson(): String {
        val gson = GsonBuilder()
	        .setPrettyPrinting()
	        .registerTypeAdapter(UObject::class.java, JsonSerializer<UObject> { 
		        src, _, _ ->
		        src.toJson()
	        })
	        .create()
        val data = rows.mapKeys { it.key.text }.mapValues { gson.toJsonTree(it.value) }
        return gson.toJson(data)
    }`
